### PR TITLE
Closes #31 Create spell checking travis test suite

### LINKED ISSUE #31: Create spell check tests for these md files
I see some grammar and spelling mistakes in the md files, it would be beneficial to have some grammar/spell checking done on these documents for each pull request with travis.

### PR DESCRIPTION
**Pull request by erikvold**

### CODE REVIEW

**Comment by erikvold** [comment]
@tofumatt r?

**Comment by tofumatt** [comment]
That is... very cool! :+1:

**Comment by lmorchard** [comment]
Small nitpick: The tests should have probably used nodeunit, since that's what we're using throughout the rest of the suite. (Though, I actually like mocha & chai better.)

**Comment by tofumatt** [comment]
Good point, I'll convert them over today.

-tofumatt

**Pull request merged**
